from .categoria import CategoriaSchema
from .despesa import DespesaSchema
from .email import EmailSchema
from .local import LocalSchema
from .marca import MarcaSchema
from .modelo import ModeloSchema
from .permissao import PermissaoSchema
from .porta import PortaSchema
from .registro_combustivel import RegistroCombustivelSchema
from .registro_porta import RegistroPortaSchema
from .tipo_combustivel import TipoCombustivelSchema
from .tipo_despesa import TipoDespesaSchema
from .tipo_problema import TipoProblemaSchema
from .usuario import UsuarioSchema
from .veiculo import VeiculoSchema
