from .categoria import Categoria
from .despesa import Despesa
from .local import Local
from .marca import Marca
from .modelo import Modelo
from .permissao import Permissao
from .tipo_combustivel import TipoCombustivel
from .tipo_despesa import TipoDespesa
from .tipo_problema import TipoProblema
from .usuario_permissao import UsuarioPermissao
from .usuario import Usuario
from .veiculo import Veiculo
